import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";

export interface CampaignPerformance {
  id: string;
  name: string;
  status: string;
  conversationsGenerated: number;
  responseRate: number;
  optOuts: number;
  totalDelivered: number;
  healthStatus: "excellent" | "regular" | "risk";
  createdAt: string;
}

export function useCampaignPerformance() {
  const { profile } = useAuth();
  const tenantId = profile?.tenant_id;

  return useQuery({
    queryKey: ["campaign-performance", tenantId],
    queryFn: async (): Promise<CampaignPerformance[]> => {
      if (!tenantId) return [];

      // Get recent campaigns
      const { data: campaigns, error: campaignsError } = await supabase
        .from("campaigns")
        .select("id, name, status, created_at, delivered_count, sent_count")
        .eq("tenant_id", tenantId)
        .order("created_at", { ascending: false })
        .limit(10);

      if (campaignsError) throw campaignsError;
      if (!campaigns || campaigns.length === 0) return [];

      // Get campaign stats
      const campaignIds = campaigns.map((c) => c.id);
      const { data: stats } = await supabase
        .from("campaign_stats")
        .select("*")
        .in("campaign_id", campaignIds);

      // Get conversations generated by each campaign
      const { data: conversationCounts } = await supabase
        .from("conversations")
        .select("id, created_at")
        .eq("tenant_id", tenantId)
        .in("status", ["open", "closed"]);

      // Map deliveries to campaigns to count responses
      const { data: deliveries } = await supabase
        .from("campaign_deliveries")
        .select("campaign_id, conversation_id, status")
        .in("campaign_id", campaignIds);

      // Calculate performance for each campaign
      return campaigns.map((campaign) => {
        const campaignStats = stats?.find((s) => s.campaign_id === campaign.id);
        const campaignDeliveries = deliveries?.filter((d) => d.campaign_id === campaign.id) || [];
        
        const conversationsGenerated = campaignDeliveries.filter(
          (d) => d.conversation_id !== null
        ).length;
        
        const totalDelivered = campaign.delivered_count || campaignStats?.messages_delivered || 0;
        const responses = campaignStats?.responses || 0;
        const optOuts = campaignStats?.opt_outs || 0;
        
        const responseRate = totalDelivered > 0 
          ? (responses / totalDelivered) * 100 
          : 0;
        
        const optOutRate = totalDelivered > 0 
          ? (optOuts / totalDelivered) * 100 
          : 0;

        // Determine health status
        let healthStatus: "excellent" | "regular" | "risk" = "regular";
        if (responseRate >= 20 && optOutRate < 2) {
          healthStatus = "excellent";
        } else if (responseRate < 10 || optOutRate >= 3) {
          healthStatus = "risk";
        }

        return {
          id: campaign.id,
          name: campaign.name,
          status: campaign.status,
          conversationsGenerated,
          responseRate: Math.round(responseRate * 10) / 10,
          optOuts,
          totalDelivered,
          healthStatus,
          createdAt: campaign.created_at,
        };
      });
    },
    enabled: !!tenantId,
  });
}
